### ISSUE TITLE
MusicBot not automatically muted when entering empty channel

### ISSUE THREAD

**Issue by Geraner** [dafoxia/mumble-ruby-pluginbot#100]
When all are leaving the channel where a MusicBot is running, the MusicBot is muting itself automatically and unmuting itself as soon as someone enters the channel again.
In the config you can pre-define which channel to connect per default. If this channel is empty when the MusicBot is connecting itself to the Mumble server, the MusicBot is not unmuting itself automatically. Only when someone enters the channel, and then leaves it again, the MusicBot is muting itself.
Please add the logic that the MusicBot even on connection to the server/channel can detect if nobody is in the channel and muting itself to not use unecessary bandwith.

**Comment by Natenom** [comment]
Should be fixed with ea9391de.

Please test and report if it works :)

**Comment by Geraner** [comment]
This issue is solved now and working. Well done! Thanks!
