### ISSUE TITLE
Feature: Simplify commands for adding songs into single command

### ISSUE THREAD

**Issue by JK2gUu-Ny9** [dafoxia/mumble-ruby-pluginbot#104]
Currently to add songs the user is required to learn and memorize multiple commands, e.g. `.add` for local files, `.ytlink`, `.bandcamp`, `.soundcloud`.
I realize there is `.[url]`, but that seems like a quick hack and is not documented yet.

depending on link target, the service type could be determined and the right handler could be used.
for example:
- no url schema => add from local database
- (?:youtube.*?(?:v=|/v/)|youtu.be/) => youtube
-  vimeo.com/([0-9]+) => vimeo

and so on. maybe even fall back to simply trying youtube-dl directly on the URL, which handles 99% of the content anyways.

**Comment by Natenom** [comment]
BTW, you can already use the command . to fetch from youtube, bandcamp, soundcloud or ektoplazm.

.URL

Though one command for all including local files is easier; will implement that :)

**Comment by JK2gUu-Ny9** [comment]
I realize there is `.[url]`, but that seems like a quick hack and is not documented yet.

**Comment by dafoxia** [comment]
Done some work already now. Bot is less spamming when you use .[url] command.
Needs still some improvements.

**Comment by JK2gUu-Ny9** [comment]
Any update on this?

**Comment by dafoxia** [comment]
I'm lack of time the last some days. Enhancements will first go into development branch, but it is not recommended to use this, because it is really full of bugs yet.

**Comment by tu-maurice** [comment]
What won't you fix? It's a feature request.
