### ISSUE TITLE
Make hardcoded superpassword configurable.

### ISSUE THREAD

**Issue by JK2gUu-Ny9** [dafoxia/mumble-ruby-pluginbot#105]
the [superpassword is currently hardcoded](https://github.com/dafoxia/mumble-ruby-pluginbot/blob/1cc000d0f1e5e7b82c8eb02944a1103b23b83732/pluginbot_conf.rb#L34) to `"kaguBe gave me all the power from kaguBe and I wish to "` and the user is not able to change it in their configuration without monkey patching.

Moving it in the same scope as the rest of the attributes should have no disadvantages.

**Comment by Natenom** [comment]
Note to myself: If we make that configurable we need to hide it from the .settings command.

**Comment by dafoxia** [comment]
Is it really a good idea to make a password with this power changeable at runtime? A troll could blacklist the bot-owner and change the password.

**Comment by Natenom** [comment]
But we could exclude the superpassword from being printed in .settings AND being changed through .set, couldn't we?

**Comment by dafoxia** [comment]
I think it may confuse users when they change the super user password and after restart, a bot kick or an error in the bot witch causes an restart it is resetted.
Better we move a option it into the extra config where it could be overwritten.

**Comment by JK2gUu-Ny9** [comment]
This appears to be solved in `devel` now.
