### ISSUE TITLE
Send an information to the user why a video is unavailable (gema, blocked),,...

### ISSUE THREAD

**Issue by Natenom** [dafoxia/mumble-ruby-pluginbot#11]

**Comment by dafoxia** [comment]
In my country there is no GEMA, but AKM (http://www.akm.at/).
It seems that Youtube/Google pay enough fees for AKM or the did'nt want so much as GEMA. The are hard to find blocked videos.
If you have a blocked video please do try a youtube-dl by hand and post me the relevant output of it. Maybe i'm able to implement some parsing to the plugin.

**Comment by Natenom** [comment]
ERROR: videoid: YouTube said: Unfortunately, this video is not available in your country because it could contain music from UMG, for which we could not agree on conditions of use with GEMA.
