### ISSUE TITLE
.ylt instantly disconnects the bot

### ISSUE THREAD

**Issue by Niichie** [dafoxia/mumble-ruby-pluginbot#110]
.yts and .yta work perfectly along with soundcloud plugins but the .ytl instantly crashes the bot.

I have updated to the latest version of the donwloader per the wiki and everything seems to be working flawlessly on the bot except for this one very important feature.

**Comment by Natenom** [comment]
Should be fixed with https://github.com/dafoxia/mumble-ruby-pluginbot/commit/9f0d7cf9b6fac76bfdf8f06fe4092be1ceaf1a54.

**Comment by Niichie** [comment]
This fixed it, thanks!
