### ISSUE TITLE
.queue doesn't work after loading a playlist.

### ISSUE THREAD

**Issue by Niichie** [dafoxia/mumble-ruby-pluginbot#111]
So to recreate this I made a playlist, then removed it. After doing so I could no longer use .queue to check the songs in the queue. I reinstalled the entire bot and everything works as it should. 

Everything still played properly even when I couldn't load the .queue, it was just annoying not knowing the number of the songs in my queue.

**Comment by dafoxia** [comment]
I can't I replicate the problem.
So there are open questions for me (to fix the bug):
How did you create the playlist?
How did you removed it?
What response did you get on the .queue command (if there is/was one) ?

**Comment by Niichie** [comment]
Okay so I created a playlist now using ".saveplaylist (name)" and added a couple songs into it. When I type ".playlist (ID)" it says that it has loaded the playlist, but plays the next song from my normal queue anyways. Now it has deleted my queue but still shows one playlists created. When I try to delete it I get the following messages.


[8:34:50 PM] Musicbot: I know the following playlists:
0 - 21
[8:34:57 PM] To Music: .delplaylist 0
[8:34:57 PM] Musicbot: Sorry, the given playlist id does not exist.
