### ISSUE TITLE
.seek (search commands not working)

### ISSUE THREAD

**Issue by Sielenc** [dafoxia/mumble-ruby-pluginbot#114]
Please see the search command for the bot. Entering .Seek currently has no function. thank you

**Comment by Natenom** [comment]
Duplicate of https://github.com/dafoxia/mumble-ruby-pluginbot/issues/113

Danke trotzdem, haette ich nicht erwartet :)

**Comment by Sielenc** [comment]
Dies scheint ja nur unter dieser Option, bei Dir so.. zu funktionieren. Danke auch ^^
