### ISSUE TITLE
After updating, bot enters chat and crashes instantly.

### ISSUE THREAD

**Issue by Niichie** [dafoxia/mumble-ruby-pluginbot#123]
As the title states, the bot now enters the room and instantly disconnects.'

This is my log in mumble.

Connection closed: The remote host closed the connection [1]
CELT codec switch ffffffff8000000b ffffffff80000010 (prefer ffffffff80000010) (Opus 1)

**Comment by dafoxia** [comment]
Please post also the output of the bot does on console.
If you followed on [Natenom's guide](https://wiki.natenom.com/w/Installation_of_mumble-ruby-pluginbot) call the startupscript with debug parameter.
` ~/src/mumble-ruby-pluginbot/scripts/start.sh debug`
and post the log file (`~/logs/pluginbots.log`)

**Comment by Downsite** [comment]
Hi, I got the same problem. I attach my log file :).


```

[killduckthread] can't kill because wrong argument type nil (expected VM/thread)
Plugin ./plugins/messages.rb loaded.
Plugin ./plugins/mpd.rb loaded.
Plugin ./plugins/bandcamp.rb loaded.
Plugin ./plugins/control.rb loaded.
Plugin ./plugins/radiostream.rb loaded.
Plugin ./plugins/ektoplazm.rb loaded.
Plugin ./plugins/soundcloud.rb loaded.
Plugin ./plugins/youtube.rb loaded.
Plugin ./plugins/null.rb loaded.
Plugin ./plugins/version.rb loaded.
Config loaded!
parse extra config
Config loaded!
pluginbot is starting...
start
/home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/opus-ruby-1.0.1/lib/opus-ruby/encoder.rb:6:in `initialize': wrong number of arguments (4 for 3) (ArgumentError)
	from /home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/audio_player.rb:123:in `new'
	from /home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/audio_player.rb:123:in `create_encoder'
	from /home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/audio_player.rb:18:in `initialize'
	from /home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/client.rb:128:in `new'
	from /home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/client.rb:128:in `player'
	from /home/botmaster/src/mumble-ruby-pluginbot/pluginbot.rb:217:in `mumble_start'
	from /home/botmaster/src/mumble-ruby-pluginbot/pluginbot.rb:565:in `block in <main>'
	from /home/botmaster/src/mumble-ruby-pluginbot/pluginbot.rb:560:in `loop'
	from /home/botmaster/src/mumble-ruby-pluginbot/pluginbot.rb:560:in `<main>'
Connecting to the server is still ongoing.
Connecting to the server is still ongoing.
connected
[killduckthread] can't kill because wrong argument type nil (expected VM/thread)

```

**Comment by dafoxia** [comment]
Hi,

please use this version of opus-ruby: https://github.com/dafoxia/opus-ruby
Sorry for not 100% compatibility of this version. It's much enhanced, a few functions are needed by the bot.
I will check if i could it get backward compatible in future, that this version could used unchanged in other projects.

**Comment by Downsite** [comment]
I tried to do step 8 "Download and set up opus-ruby" while  cloning this repo to a different folder. and it installed, but the error comes up again, and after using the maintance tool produces the log I have appended, but don't force yourself to find a bug in, my setup might be messed up by now, I think I will reload the image and do a fresh start:
```
/home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- celt-ruby (LoadError)
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/botmaster/.rvm/gems/ruby-2.1.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby.rb:2:in `<top (required)>'
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/botmaster/src/mumble-ruby-pluginbot/pluginbot.rb:6:in `<main>'
/home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- celt-ruby (LoadError)
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/botmaster/.rvm/gems/ruby-2.1.1@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby.rb:2:in `<top (required)>'
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/botmaster/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/botmaster/src/mumble-ruby-pluginbot/pluginbot.rb:6:in `<main>'
```

**Comment by dafoxia** [comment]
this log causes a missing celt-ruby gem.
Don't forget the celt library to build when you install this gem. The bot will crash if server want to switch to celt instead.

**Comment by Downsite** [comment]
I set a new image up, and it works flawlessly now, but  I hesitate to update now, what would be the right way to update the bot from the bananapi Image, without breaking it again  ;).

**Comment by dafoxia** [comment]
I can't test at the moment, but a `git pull` in the mumble-ruby-pluginbot folder and after that a `./scripts/update.sh` should you bring a menu.
In this menue update all is the right way now.

**Comment by Biosha** [comment]
Hi, I got the same problem but not the same logs.

Here are mine [pluginbots.txt](https://github.com/dafoxia/mumble-ruby-pluginbot/files/123994/pluginbots.txt) 

It's weird, the bot connect in the channel and disconnect immediatly...

**Comment by dafoxia** [comment]
Are your settings correct?

See pluginbot_conf.rb

In your case this section is maybe misconfigured.

 ###########################
 # Mpd plugin: #############
 ###########################
 @settings[:mpd_musicfolder] = "/home/botmaster/music/"
 # This is not used in the "Mpd plugin" itself but is needed by
 # other plugins.
 # Set this to the same path that you set in your mpd config
 # file in the variable music_directory.

**Comment by Biosha** [comment]
Settings are correct because the bot correctly connect in the good channel. 

I've just open the pluginbot_conf.rb (no edit) and launch start.sh and now another error is in the logs.

[pluginbots.txt](https://github.com/dafoxia/mumble-ruby-pluginbot/files/126826/pluginbots.txt)

I run it on a RPI, maybe the issue come form my config ?

**Comment by dafoxia** [comment]
Sorry for my heavy delay.....
This happens when you install the wrong opus gem.
Please use that one: https://github.com/dafoxia/opus-ruby
There was an API-change. :/

**Comment by BattleGear** [comment]
have the same error and updated the opus_ruby via gem install opus-ruby and still have the same error...

**Comment by dafoxia** [comment]
Please remove the opus-ruby-gem and redo step 8 in Natenom's guide.
(https://wiki.natenom.com/w/Installation_of_mumble-ruby-pluginbot)

> 8 Download and set up opus-ruby
> cd ~/src
> git clone https://github.com/dafoxia/opus-ruby.git
> cd opus-ruby
> rvm use @bots
> gem build opus-ruby.gemspec 
> rvm @bots do gem install opus-ruby

**Comment by BattleGear** [comment]
ive delete the user botmaster and started from skretch and now it works... the only problem i have now is the sound stutter like hell with a 100 mbit connection. messed around with the buffer settings but nothing changes... think my rpi 1 is on his limit! or have you any ideas?

**Comment by dafoxia** [comment]
Your rpi1 is on cpu limit.
A raspberry 2, banana pi, banana pi m2 or m3  work smooth.
For a raspi 2 there is a ready image based on debian jessy, for the banana pi / pi-m2 there are images based on armbian.
Don't forget to update the distro and the pluginbot to be actual.
