### ISSUE TITLE
setting "volume: nil" crashes bot when sending .v command

### ISSUE THREAD

**Issue by Natenom** [dafoxia/mumble-ruby-pluginbot#135]
IIRC this is described in the documentation when the user doesn't want to have an initial volume set on connect but instead the last volume that was set.

**Comment by dafoxia** [comment]
Since the volume could not read from ruby-mpd, I will set the function to do a feedback that it sends in unknown volume instead of crash.

**Comment by Natenom** [comment]
Fixed
