### ISSUE TITLE
pluginbot won't play fragradio radiostream (portnumber in playlist url)

### ISSUE THREAD

**Issue by israuor** [dafoxia/mumble-ruby-pluginbot#139]
found a radiostream the bot wouldn't play.. 

stream.fragradio.co.uk:8000/autodj.m3u
looks like bot doesn't like links to playlist containing a port number. 

greetings from the f*** middle east

**Comment by dafoxia** [comment]
Confirmed, needs deeper stream inspection to see if it is a real bug.

**Comment by dafoxia** [comment]
It is a Mpeg2/AAC Stream witch the bot can't handle at the moment. Since I can't find information how to detect all of the different implementation of stream (TransportStream, ProgramStream and/or capsuled and multiplexed with video) a implementation won't go in.
