### ISSUE TITLE
Bandcamp link crashes bot

### ISSUE THREAD

**Issue by israuor** [dafoxia/mumble-ruby-pluginbot#142]
Earlier this morning I treed to feed a bandcamp link to the bot.. (link to complete album) 
.http://atthegraves1.bandcamp.com/album/at-the-graves
or
.bandcamp http://atthegraves1.bandcamp.com/album/at-the-graves

crashes the bot.. and he's not coming back.

**Comment by Natenom** [comment]
Error: An error occurred: undefined method `[]' for nil:NilClass
Error: Backtrace: ["/home/mumble-ruby-pluginbot/plugins/bandcamp.rb:106:in `get_song'", "/home/mumble-ruby-pluginbot/plugins/bandcamp.rb:62:in `block in handle_chat'"]

**Comment by Natenom** [comment]
Error output of the bot (devel branch) for the youtube plugin.

Error: An error occurred: undefined method `[]' for nil:NilClass
Error: Backtrace: ["/home/botmaster/src/mumble-ruby-pluginbot/plugins/radiostream.rb:125:in `add_link'", "/home/botmaster/src/mumble-ruby-pluginbot/plugins/radiostream.rb:44:in `block in handle_chat'"]

**Comment by Natenom** [comment]
Can be fixed by removing the radiostream plugin.
