### ISSUE TITLE
Bot connects and crashes

### ISSUE THREAD

**Issue by BattleGear** [dafoxia/mumble-ruby-pluginbot#153]
hi

ive installed the bot after the manuel and the install worked. but now ive got a problem...

after the bot joines the server and switch to the channel he leaves the server...

on start script comes a error message with some smb stuff:

botmaster@osmc:~/logs$ ~/src/mumble-ruby-pluginbot/scripts/start.sh
Updating youtube-dl...
youtube-dl is up-to-date (2016.04.13)
Killing running ruby scripts of user botmaster
Killing running mpd instances of user botmaster
params.c:OpenConfFile() - Unable to open configuration file "/home/botmaster/.smb/smb.conf.append":
        No such file or directory
Using /home/botmaster/.rvm/gems/ruby-2.3.0 with gemset bots

Your bot(s) should now be connected to the configured Mumble server.

_LOGGING/DEBUGGING_
  If something doesn't work, start this script with the additional parameter debug:
  ~/src/mumble-ruby-pluginbot/scripts/start.sh debug

  Then take a look into the logfile within /home/botmaster/logs/.

_START AS APPROPRIATE USER_
  Make sure to run this script as user botmaster if you used the official
  installation documentation and DO NOT RUN THIS SCRIPT AS root.
  The official documentation can be found at https://wiki.natenom.com/w/Mumble-Ruby-Pluginbot

_UPDATE THE BOT (AND ITS DEPENDENCIES)_
  If you want to update the Mumble-Ruby-Pluginbot (and its dependencies) please
  run ~/src/mumble-ruby-pluginbot/scripts/updater.sh

_OFFICIAL DOCUMENTATION_
  Also please reread the official documentation at https://wiki.natenom.com/w/Mumble-Ruby-Pluginbot
  if you have further problems :)

_BUGS/WISHES/IDEAS_
  If you think you found a bug, have a wish for the bot or some ideas please don't
  hesitate to create an issue at https://github.com/dafoxia/mumble-ruby-pluginbot/issues

Have fun with the Mumble-Ruby-Pluginbot :)

and the log file meanes:

Config loaded!
parse extra config
Own Config loading and overwriting default settings!
pluginbot is starting...
start
/home/botmaster/.rvm/gems/ruby-2.3.0@bots/gems/opus-ruby-1.0.1/lib/opus-ruby/en$
        from /home/botmaster/.rvm/gems/ruby-2.3.0@bots/gems/mumble-ruby-1.1.3/l$
        from /home/botmaster/.rvm/gems/ruby-2.3.0@bots/gems/mumble-ruby-1.1.3/l$
        from /home/botmaster/.rvm/gems/ruby-2.3.0@bots/gems/mumble-ruby-1.1.3/l$
        from /home/botmaster/.rvm/gems/ruby-2.3.0@bots/gems/mumble-ruby-1.1.3/l$
        from /home/botmaster/.rvm/gems/ruby-2.3.0@bots/gems/mumble-ruby-1.1.3/l$
        from /home/botmaster/src/mumble-ruby-pluginbot/pluginbot.rb:185:in `blo$
Connecting to the server is still ongoing.
Connecting to the server is still ongoing.
connected
[killduckthread] can't kill because wrong argument type nil (expected VM/thread)

have somebody any idea how i get this to work?!?

**Comment by dafoxia** [comment]
Are parts of botmasters home mounted by samba?
Is samba configuration working?
...params.c:OpenConfFile() - Unable to open configuration file "/home/botmaster/.smb/smb.conf.append":
**No such file or directory**
