### ISSUE TITLE
The link contains nothing interesting, and reconnects 

### ISSUE THREAD

**Issue by dominos96** [dafoxia/mumble-ruby-pluginbot#156]
I have problem with some links on yt.
When i write .ytlink {my link}, i recive:
Youtube is inspecting link: {my link}
Youtube: The link contains nothing interesting.

And when downloads a file from youtube in mp3 format, bot reconnects to server, and nothing is downloaded.

Sorry for my english ;)

**Comment by dominos96** [comment]
I try this https://github.com/dafoxia/mumble-ruby-pluginbot/issues/45
but it did not help

**Comment by dafoxia** [comment]
Please post your debug log.
You can enable it once by ``~/src/mumble-ruby-pluginbot/scripts/start.sh debug``
Your logfile is then in ` `~/logs/pluginbots.log``

For a complete and functional installation of the bot you could read and use [Natenom's manual](https://wiki.natenom.com/w/Installation_of_mumble-ruby-pluginbot).
Debug is there in [section 12] (https://wiki.natenom.com/w/Installation_of_mumble-ruby-pluginbot#Finish_it.2C_run_your_bot.28s.29).

**Comment by dafoxia** [comment]
No response from Thread-opener, closed.
