### ISSUE TITLE
Bot won't connect to murmur server that I'm hosting.

### ISSUE THREAD

**Issue by Niichie** [dafoxia/mumble-ruby-pluginbot#157]
Basically taking advantage of AWS free tier EC2 hosting. I managed to get the bot working on Ubuntu after a lot of googling only to find that I can't make it connect to the murmur server that I'm hosting in the same instance.

I can connect to the murmur server, so can all my friends, and the bot can connect to my typefrag server, but not the one i'm hosting.

**Comment by robingroppe** [comment]
Show your Config please.

**Comment by dafoxia** [comment]
No response, closed.
