### ISSUE TITLE
Adding a comment to the bot

### ISSUE THREAD

**Issue by ReekyMarko** [dafoxia/mumble-ruby-pluginbot#158]
I would like to have a comment for my music bot, so I grabbed the bot certificate, logged on to my server and added an avatar and a comment for the bot, logged out and started the bot.

The avatar worked fine but the comment seems to get overwritten during bot startup. Is this something I can disable using the bot config?

**Comment by dafoxia** [comment]
In your config set `use_comment_for_status_display: false,`
It's true in default config. The spam some information to chat instead to comment.

HTH
