### ISSUE TITLE
.settings in wrong help

### ISSUE THREAD

**Issue by tu-maurice** [dafoxia/mumble-ruby-pluginbot#162]
Command .settings is in the help of mpd not in the help of internals. (im devel-Branch)

**Comment by Natenom** [comment]
Fixed with https://github.com/dafoxia/mumble-ruby-pluginbot/commit/146c35006ea61142ae00891b43c5bf834c6c70db

**Comment by tu-maurice** [comment]
Did you add it somewhere else in the help?

**Comment by Natenom** [comment]
It was already in .internals...

.settings in mpd was probably a leftover from earlier development.

**Comment by tu-maurice** [comment]
Oh okay.
