### ISSUE TITLE
Please don't retry to join a channel when no permissions when using .follow and maybe also write a message to the user...

### ISSUE THREAD

**Issue by Natenom** [dafoxia/mumble-ruby-pluginbot#20]
Jun  6 22:57:46 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:46 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:47 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:47 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:48 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:48 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:49 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:49 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:50 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:50 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:51 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:51 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:52 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:52 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:53 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:53 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:54 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:54 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:55 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:55 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:56 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:56 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:57 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:57 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:58 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:58 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:59 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:57:59 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:00 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:00 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:01 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:01 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:02 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:02 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:03 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:03 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:04 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:04 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:05 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:05 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:06 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:06 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:07 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:07 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:08 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:08 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:09 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:09 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:10 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:10 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:11 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:11 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:12 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:12 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:13 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:13 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:14 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:14 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat
Jun  6 22:58:15 ip-ip-ip-ip murmurd[pid]: 1 => <31:<E2><99><AB> Bot3 (f<C3><BC>r alle)(2506)> <E2><99><AB> Bot3 (f<C3><BC>r alle) not allowed to Enter in Privat

**Comment by dafoxia** [comment]
Bot stop's following when it get a permission denied message.
