### ISSUE TITLE
Feature Request: Sleepbot and Wakebot

### ISSUE THREAD

**Issue by Stunner1984** [dafoxia/mumble-ruby-pluginbot#22]
Is it possible to implement a feature similar to .wakeup when a user enters a channel with a bot and .gotobed when a bot is the only user in a particular channel?

Reason for asking is Ruby is using a lot of system resources when running especially running 2 bots at the same time.  It would be nice to have them shut themselves down if nobody is "listening" and wake up when someone enters a channel with a bot already in it.  

I am attempting to write a python script for mumo that does just this but if it can be implemented as a plugin let me know, thanks.

**Comment by dafoxia** [comment]
Pausing automatic feature if bot is alone is planned AS enhancement in near future. Hope that helps.

**Comment by Stunner1984** [comment]
It does thanks I will proceed with my project and let you know how it goes.

**Comment by dafoxia** [comment]
PS: Automute is deactivated per default. 
You have to set `@settings[:control_automute] = true` in your config to enable it on start.

**Comment by Stunner1984** [comment]
Thanks, I did enable that on mine I also added:
@bot[:mpd].pause = true and
@bot[:mpd].pause = false 

to simulate .gotobed and .wakeup commands when nobody is in the channel
