### ISSUE TITLE
Bot not able to find manually added files

### ISSUE THREAD

**Issue by GamerBene19** [dafoxia/mumble-ruby-pluginbot#249]
Steps to reproduce
1. Add file to some of the `music` subfolders (e.g. `downloadedfromyt`)
2. `.songlist` does not print the file (as expected)
3. Run `.update`
4. `.songlist` now _does_ print the file
5. `.where <serachstring>` is not able to find the song (while songs that were downloaded from youtube do work)

I also tried manually adding the song to the queue with an mpd client - which worked.

**Comment by dafoxia** [comment]
Sounds like the file you added has no propper tags.
`.where <searchstring>` only works on tag at the file, not at the filename.
Use a file tagger before, I like to use MusicBranz Picard, but you could use basically anyone.

**Comment by GamerBene19** [comment]
> Sounds like the file you added has no propper tags. `.where <searchstring>` only works on tag at the file, not at the filename. Use a file tagger before, I like to use MusicBranz Picard, but you could use basically anyone.

Ah makes sense. Would be nice if it was documented and even nicer if there was a way to add files by their names directly :thinking:
