### ISSUE TITLE
add ionice -c3 to the console commands or make it visable in the config

### ISSUE THREAD

**Issue by netinetwalker** [dafoxia/mumble-ruby-pluginbot#25]
nice -n20 ionice -c3 COMMAND

please give package info to natenom ... package util-linux (debian)

**Comment by dafoxia** [comment]
You can set now command prefixes in the config.
Use` @settings[:youtube_commandlingefrefixes]` for youtube-plugin and `@settings[:soundcloud_commandlineprefixes]` for soundcloud plugin.

**Comment by Natenom** [comment]
Thanks for the package info ... updated in the documentation.
