### ISSUE TITLE
Seek

### ISSUE THREAD

**Issue by jjellinek** [dafoxia/mumble-ruby-pluginbot#26]
File longer than 999 seconds, couldn't seek in one go. Suggest allowing at least 9999 if not more?

**Comment by dafoxia** [comment]
I will write sind code for seeking not only in seconds. Probeably seek 12:45 to seek to Position 2 minutes and 45 seconds. Titles oder 99 hours oft playtime should not occur. :)

**Comment by dafoxia** [comment]
Seeking in pure second search is still limited to 999. I don't think a normal human calculate first the seconds to search then.
Use `seek 16:36` to jump on second 999 instead. (And `seek +2:46:36` to fast forward to second 9999)
:relieved:
If you still want greater seek ranges in pure second typing leave a message, instead I think I can close.
:smiley:

**Comment by jjellinek** [comment]
This is great thank you.
