### ISSUE TITLE
Feature request: Playlist / Queue delete individual

### ISSUE THREAD

**Issue by jjellinek** [dafoxia/mumble-ruby-pluginbot#27]
I'm sure you must already be working on this, but it would be very useful to be able to delete items from the queue (I see they are numbered now) and also whole playlists.

Thanks for this great project!

**Comment by dafoxia** [comment]
Changed numbering songlist. Songs are numberd from 0 instead from 1 now.
Fits now to internal mpd order.

**Comment by Natenom** [comment]
Ability to remove playlists implemented with 16d7e11
