### ISSUE TITLE
Only 1 bot gets paused when running start.sh on first boot of the day

### ISSUE THREAD

**Issue by Stunner1984** [dafoxia/mumble-ruby-pluginbot#30]
Even after changing user_count < 3 on first boot of the start.sh script only bot1 gets paused, when using 2 bots to connect to the same channel.

If I enter and exit the channel with a user they both pause as they should.

EDIT: After some testing it seems like the bot is not counting itself when starting the start.sh script and once the second bot joins it then counts the user state change but only auto pauses the first bot that entered the channel.

Possible to add or move parts of the auto start script to a def connected rather than def userstate?

**Comment by dafoxia** [comment]
The bot only react on user-state changes. But it react on ANY user-state changes. That means if the first user changes a room or join or left the server it will react with muting and pausing itself (If conditions for muting given).
If you want your bots not to play when the join the server it's the best to pause mpd in start-script.

If this is not your wanted behavior of the bot please describe HERE on witch condidion should happen what.
I'll read it then if I'm not burned out after a long day and try to implement

**Comment by Stunner1984** [comment]
I will try and explain a bit better.

I have 2 bots that connect everyday at 9:00 am after a server reboot the previous night.

The start.sh script will connect 1 bot then the other, bot 1 registers that a userstate change has occurred when bot 2 enters and mutes and pauses itself. Bot 2 never mutes or pauses unless I enter the channel with another user then everything works as intended.

I guess your comment about having the bots start up paused would fix this issue.  Just wasn't sure if there was a way to have bot 2 also capture that it should also mute/pause itself by adding the script in a def connected rather than def userstate change.

**Comment by dafoxia** [comment]
That is true. It is generally no good idea to set a bot per _default_ into a self unmuting and playing status.
When a user logged of the previous day in a channel where the bot was and return on the next day.... the first he was hear is .......   S   O   U   N   D   !   !   !  
Maybe a other user has turnd up the volume to max.
--> heart attack :broken_heart: :smiling_imp:
