### ISSUE TITLE
This link contains nothing interesting..

### ISSUE THREAD

**Issue by Downsite** [dafoxia/mumble-ruby-pluginbot#45]
Hi,
I downloaded your banana pi image and updated ruby youtube-dl etc.
Youtube-dl on its own is fine, but .ytlink https://www.youtube.com/watch?v=6fn6W5yyjBk returns:
 Banana1: Youtube is inspecting link: https://www.youtube.com/watch?v=v=6fn6W5y...
[12:55:03] Banana1: Youtube: The link contains nothing interesting.
Same goes for Bandcamp plugin.

**Comment by dafoxia** [comment]
Please change in bot1_conf.rb the line 
`@settings[:youtube_youtubedl] = "/usr/bin/youtube-dl"` 
into 
`@settings[:youtube_youtubedl] = "/home/botmaster/src/youtube-dl"`
then 
`cd /home/botmaster/src/mumble-ruby-pluginbot/`
and run 
`git pull`
now you should have the most recent version and all should work.

**Comment by Downsite** [comment]
##### Thank you very much,

That line was completly missing, works like a charm now after a restart.

**Comment by GamerBene19** [comment]
I do have the same problem.
I can´t find a file named bot1_conf.rb. Where do I need to change the lines?
