### ISSUE TITLE
Pi bot is not joining my server also MPD error

### ISSUE THREAD

**Issue by VanillaWaferX** [dafoxia/mumble-ruby-pluginbot#46]
So I installed this on a raspberry pi 2 with the pre configured image. The bot starts at boot but does not join my server. I made sure the config file had my server info in it and a username and targetchannel. 

Also at start up I get this

Killing running ruby scripts of user "botmaster"
errno: Failed to open /home/botmaster/mpd2/mpd.conf:No such file or directory
errno: Failed to open /home/botmaster/mpd2/mpd.conf:No such file or directory
Killing running ruby scripts of user "botmaster"
Using /home/botmaster/.rvm/gems/ruby-2.2.1 with gemset bots
http://ogg.theradio.cc/

**Comment by VanillaWaferX** [comment]
Okay so I actually found the issue. The pi 2 is actually not connecting to my network. Now the issue is I cant login as root. Just get an authentication failure.

**Comment by dafoxia** [comment]
Since the images for the raspberry and the banana a little bit old I recommend to update your bot.
Log in as botmaster user and 
`cd /home/botmaster/src/mumble-ruby-pluginbot/`
then  run
`git pull`
now you should have the most recent version and all should work.

PS: see in /src/mumble-ruby-pluginbot/pluginbot_conf.rb for new feature settings.
Without set the settings in your bot1_conf.rb you can't use the new features!

**Comment by VanillaWaferX** [comment]
I attempted to update to the latest using the "git pull" command and I get the error
[code]Please, commit your changes or stash them before you can merge.
Aborting[/CODE]

**Comment by dafoxia** [comment]
Please delete or rename your start.sh in folder /home/botmaster/src/mumble-ruby-pluginbot.
After this a git pull will work.
You just loose some additional help for first start on HDMI output.

I want you to point out emphatically that the configuration must be adapted to the new plugins work.

If the bot still left your server after connect please post your logbot1.log found in /home/botmaster/src/mumble-ruby-pluginbot/

**Comment by dafoxia** [comment]
Please reopen when problem is not fixed by last post.
