### ISSUE TITLE
History command makes the bot crash

### ISSUE THREAD

**Issue by cataldoc** [dafoxia/mumble-ruby-pluginbot#47]
Hello

for some strange reasons when I send the .history command the bot gets disconnected from mumble and then comes back. As far as I can see it does not crash (the process does not get restarted) and I just get the bot disconnected and reconnect again with zero history to show. 

I have the history set to the default (20) @settings[:control_historysize] = 20

this is from murmurd.log

(blue it's me, connecting and asking the .history to the bot, which immediately disconnect)

<W>2015-08-13 11:16:04.032 1 => <123:(-1)> New connection: XXXXXX:50449
<W>2015-08-13 11:16:04.129 1 => <123:(-1)> Client version 1.3.0 (WinX64: 1.3.0~704~g6fe5547~snapshot)
<W>2015-08-13 11:16:04.137 1 => <123:Blue(189)> Authenticated
<W>2015-08-13 11:16:30.706 1 => <80:MumbleBot(190)> Connection closed: The TLS/SSL connection has been closed [1]
<W>2015-08-13 11:16:30.709 1 => CELT codec switch ffffffff8000000b ffffffff80000010 (prefer ffffffff80000010) (Opus 1)
<W>2015-08-13 11:16:31.210 1 => <124:(-1)> New connection: 127.0.0.1:33779
<W>2015-08-13 11:16:31.248 1 => <124:(-1)> Client version 1.2.7 (Linux: mumble-ruby 1.1.2)
<W>2015-08-13 11:16:31.292 1 => CELT codec switch ffffffff8000000b ffffffff80000010 (prefer ffffffff8000000b) (Opus 1)
<W>2015-08-13 11:16:31.298 1 => <124:MumbleBot(190)> Authenticated

this is what I see in mpd1.log

Aug 13 11:16 : client: [6] opened from [::1]:36839

**Comment by dafoxia** [comment]
When a user has left the server and he is on history list this error occure.
Start to work on it now. :)

**Comment by cataldoc** [comment]
Hi, It seems the latest commit broke the .queue command, I did an update... now history is working fine, but queue shows nothing (even tho I know there are songs in the queue)

**Comment by dafoxia** [comment]
I can not determine the error with me. Did you get an empty list or no feedback?

**Comment by cataldoc** [comment]
I updated again (I saw the mpd plugin was updated few hours ago) and now it's working again... I was getting no feedback at all btw.

I really love your work guys, thank you :)

**Comment by dafoxia** [comment]
Did you get a feedback for any other command?
Please check also the ".stats" command. It is in the same plugin coded and if it works ".queue" should also do.

**Comment by cataldoc** [comment]
Hi, the last git pull I did 3 days ago everything is working fine again... history, queue, stats and all the other commands gives me feedback.
