### ISSUE TITLE
Bot cannot join server

### ISSUE THREAD

**Issue by qtruong1996** [dafoxia/mumble-ruby-pluginbot#56]
I get this error every time it starts.
Mumble server works, but bot doesn't join.

This is for running script as botmaster:

Killing running mpd instances of user "botmaster"
listen: bind to '[::1]:7701' failed: Failed to create socket: Address family not                                                                supported by protocol (continuing anyway, because binding to '127.0.0.1:7701' s                                                               ucceeded)
daemon: cannot init supplementary groups of user "botmaster": Operation not perm                                                               itted
Killing running ruby scripts of user "botmaster"
Using /home/botmaster/.rvm/gems/ruby-2.2.1 with gemset bots
volume:100%   repeat: off   random: off   single: off   consume: off
http://ogg.theradio.cc/
[playing] #1/1   0:00/0:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: off

This is what I get for trying to sudo the start.sh, I get:

mkdir: cannot create directory `/home/botmaster/logs': File exists
Killing running mpd instances of user "root"
listen: bind to '[::1]:7701' failed: Failed to create socket: Address family not supported by protocol (continuing anyway, because binding to '127.0.0.1:7701' succeeded)
Killing running ruby scripts of user "root"
/home/botmaster/src/mumble-ruby-pluginbot/start.sh: line 34: /root/.rvm/scripts/rvm: No such file or directory
/home/botmaster/src/mumble-ruby-pluginbot/start.sh: line 35: rvm: command not found
volume:100%   repeat: off   random: off   single: off   consume: off
http://ogg.theradio.cc/
[playing] #1/1   0:00/0:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: off

I did a full refresh install(OS, mumble and pluginbot) with copy and paste from the tutorial. I tried the solution from other forum suggesting to remove #USER in the mpd.conf, but none work.

**Comment by Natenom** [comment]
> /home/botmaster/src/mumble-ruby-pluginbot/start.sh: line 34: /root/.rvm/scripts/rvm: No such file or directory

Are you starting the script as root for which you didn't setup a ruby environment through rvm like described in the documentation?

Try to run the script as user botmaster.

**Comment by qtruong1996** [comment]
botmaster@raspberrypi ~/src $ ~/src/mumble-ruby-pluginbot/start.sh
mkdir: cannot create directory `/home/botmaster/logs': File exists
Killing running mpd instances of user "botmaster"
listen: bind to '[::1]:7701' failed: Failed to create socket: Address family not supported by protocol (continuing anyway, because binding to '127.0.0.1:7701' succeeded)
daemon: cannot init supplementary groups of user "botmaster": Operation not permitted
Killing running ruby scripts of user "botmaster"
Using /home/botmaster/.rvm/gems/ruby-2.2.1 with gemset bots
volume:100%   repeat: off   random: off   single: off   consume: off
http://ogg.theradio.cc/
[playing] #1/1   0:00/0:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: off

This is what I get for running as botmaster

**Comment by Natenom** [comment]
Looks good; you should have a running bot on the configured server after that...

Note to myself: Add a short message that everything was fine into the script :)

In case there is no bot on your server please start the script with the additional parameter debug:
~/src/mumble-ruby-pluginbot/start.sh debug

Then open the logfile in /home/botmaster/logs/ and post last lines of that file; probably on a paste service :)

**Comment by qtruong1996** [comment]
Mine works, it seems like naming the room "Internet Radio" causes a bit of trouble for the bot to join. I renamed to "Radio" and now I see the bot.

**Comment by Natenom** [comment]
Nice, so I can close this issue :)

Note to myself: Startscript notes implemented, see #57
