### ISSUE TITLE
Not able to join with error in logs (no idea what it means)

### ISSUE THREAD

**Issue by adtlocke** [dafoxia/mumble-ruby-pluginbot#58]
Raspberry Pi 2 following installation instructions

ran as botmaster and not root
pluginbots.log on pastebin:
http://pastebin.com/BxtNdgQw

seems to be an issue with loading a gem?
Thanks for any help

Also the server has a password on it (took the pass off to test and still didn't work). Is there a setting for the server password or is that just the userpass?

**Comment by Natenom** [comment]
Please run:
 find /home/botmaster -iname "*mumble-ruby*"

Doesnt' matter as which user, root or botmaster.

There should be a directory named /home/botmaster/.rvm/gems/ruby-2.2.1@bots/gems/mumble-ruby-1.1.2

If it finds a directory named without "@bots" in its name or no such directory you missed something in the tutorial.

**Comment by adtlocke** [comment]
Thanks so much, it works.

Information for anyone else having this issue:

Error when the pastebin link expires:
/home/botmaster/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mumble-ruby (LoadError)

Make sure you have the * when you run the command "rvm @bots do gem install mumble-ruby-*.gem"

And userpassword is also server password.
