### ISSUE TITLE
Youtube-dl Plugin Music folder path detection

### ISSUE THREAD

**Issue by MinaTheLoli** [dafoxia/mumble-ruby-pluginbot#9]
youtube dl adds 2 paths while downloading a video
@settings[:mpd_musicfolder] = ""    <--- empty fixed the error

**Comment by dafoxia** [comment]
I didn't really understand what you mean exactly, but it is true: youtube plugin creates 2 directorys.
One for temporary use, the other one should be in your mpd's music folder and is for holding songs and preview pictures for longer time.
In the moment the plugin does'nt implement no cleanup for the temporary folder, so you have to do it by hand from time to time. 
There is already planned a method to do this by a plugin-command.
**Finally I think that it is no good idea to leave the path to the musicfolder empty.
This may affect plugins written in the future.**
I've merged a pull request https://github.com/Natenom/mumble-ruby-pluginbot/commit/1d7305f885dcbbd55f125c5298312cb5c0422f70 a few hours ago.
Now the config is much more read- and understandable.
:grinning:
