### ISSUE TITLE
add ability to play non pls streams

### ISSUE THREAD

**Issue by Natenom** [dafoxia/mumble-ruby-pluginbot#90]

**Comment by dafoxia** [comment]
done with https://github.com/dafoxia/mumble-ruby-pluginbot/commit/05f5b3ea6b31f2c4419547956789c99e8ac79293

**Comment by dafoxia** [comment]
Done with https://github.com/dafoxia/mumble-ruby-pluginbot/commit/526191526f213a3e866de150404a88e4d5751b32: parsing of xspf links.
Get sure installed gem "crack" on your system, else this function is disabled.

**Comment by dafoxia** [comment]
Most common formats work now. Reopen if a specific stream format is missing.
