### ISSUE TITLE
parse pls files correctly

### ISSUE THREAD

**Issue by Natenom** [dafoxia/mumble-ruby-pluginbot#91]
1. Add all http urls from a .pls file to the queue.
2. regex for finding urls instead of fix length which fails if there are more than 10 files in a pls which crashes the bot...

https://en.wikipedia.org/wiki/PLS_%28file_format%29

**Comment by Natenom** [comment]
@dafoxia Isn't that already implemented?

**Comment by dafoxia** [comment]
Testing done.
